name: pull-request

on:
  workflow_dispatch:


jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents:      read
      id-token:      write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.2"
      
      # - uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: "provide role name "
      #     role-session-name: 'GitHub_to_AWS_via_FederatedOIDC'
      #     aws-region: "us-east-1"
      #     role-duration-seconds: 3600

      - run: terraform init -input=false
        env:
          # TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
          TF_VAR_jfrog_token: ${{ secrets.JFROG_TEST_OIDC }}  


      - run: terraform plan -input=false -out .tfplan
        env:
          # TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
          TF_VAR_jfrog_token: ${{ secrets.JFROG_TEST_OIDC }} 
                  
      - uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ github.token }}
          planfile: .tfplan

  
